### ISSUE TITLE
Error en el primer ejercicio de bucles

### ISSUE THREAD

**Issue by rcedazo** [informatica-ieef-etsidi/condicionales-bucles-e105-ee105#1]
Por favor, que alguien revise este código que tiene errores. 

Fichero: Ejercicio1-bucles.c

Cuando lo resolváis, por favor, cerrad el "issue" que acabo de abrir y que os llegará por e-mail. Hablaremos de los "issues" en la próxima clase.

Gracias

**Comment by Alejandrolopezguerrero** [comment]
El código ya está corregido
