### ISSUE TITLE
El ejercicio 14 de bucles requiere un switch

### ISSUE THREAD

**Issue by rcedazo** [informatica-ieef-etsidi/condicionales-bucles-e105-ee105#3]
En el enunciado dice que hay que programarlo con switch. En cualquier caso, el programa debería utilizar "if-else if" en vez de todo con if, ya que según está va a realizar todas las comprobaciones.

Ejercicio14-bucles.c

Saludos

**Comment by AnaDue99** [comment]
El código está corregido con else-if y el ejercicio lo he subido resulto respondiendo a los requerimientos del enunciado.
